// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zzfyvjlqzblvufeoqslr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp6Znl2amxxemJsdnVmZW9xc2xyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyNjI3ODcsImV4cCI6MjA2NzgzODc4N30.EeL_FX3LF303N2V4_4FclHTWp6Y8Zt0W-Vb6vwB18z8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});